_wandb:
    value:
        cli_version: 0.27.2
        e:
            1wk0j9b007yjp6px8sbn3fo65dvvf8uk:
                args:
                    - --steps
                    - "20000"
                    - --latent-n
                    - "16"
                    - --latent-d
                    - "512"
                    - --n-cross
                    - "2"
                    - --n-self
                    - "3"
                    - --warmup
                    - "500"
                    - --run-name
                    - stage1_distill_k256_big
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "481593462784"
                        used: "43086995456"
                email: mbonsign@gmail.com
                executable: /home/bard/Code/HN/peer-adaptive-k/.venv/bin/python
                git:
                    commit: 0907f7ea1352c777ee8c609a1723f76e8ee9ff22
                    remote: git@github.com:MikeyBeez/HyperPEER.git
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 8960
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-e11e9349-ebd9-48e9-10d2-7d57ffd730b5
                host: pop-os
                memory:
                    total: "33570021376"
                os: Linux-6.18.7-76061807-generic-x86_64-with-glibc2.39
                program: -m experiments.distill_stage1
                python: CPython 3.12.3
                root: /mnt/data/Code/HN/HyperPEER
                startedAt: "2026-06-10T17:39:23.357974Z"
                writerId: 1wk0j9b007yjp6px8sbn3fo65dvvf8uk
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 41
            "4": 3.12.3
            "5": 0.27.2
            "12": 0.27.2
            "13": linux-x86_64
batch:
    value: 2
ckpt_every:
    value: 1000
ctx:
    value: 256
eval_batches:
    value: 8
eval_every:
    value: 250
k_gen:
    value: 256
latent_d:
    value: 512
latent_n:
    value: 16
log_every:
    value: 25
lr:
    value: 0.0001
n_cross:
    value: 2
n_self:
    value: 3
no_wandb:
    value: false
run_name:
    value: stage1_distill_k256_big
seed:
    value: 1337
steps:
    value: 20000
tau:
    value: 1
warmup:
    value: 500
